# tags rule
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

# window rules
windowrule = isfloating:1, appid:thunar
windowrule = isfloating:1, appid:thunar, title:Rename
windowrule = isfloating:1, appid:thunar, title:Bulk Renamer
windowrule = isfloating:1, appid:thunar, title:Properties
windowrule = isfloating:1, appid:thunar, title:Confirm to replace files
windowrule = isfloating:1, appid:thunar, title:File Operation Progress
windowrule = isfloating:1, appid:thunar, title:Open File
windowrule = isfloating:1, appid:thunar, title:Save File

windowrule=isfloating:1,title:Authentication required
windowrule=isfloating:1,title:Keybindings
windowrule=isfloating:1,title:Rename*
windowrule=isfloating:1,title:Compressing*
windowrule=isfloating:1,title:File Already Exists*
windowrule=isfloating:1,title:Extracting Files*,
windowrule=isfloating:1,title:File Operation Progress*
windowrule=isfloating:1,title:Confirm to replace files*
windowrule=offsety:96%,offsetx:98%,isnoborder:1,isopensilent:1,isoverlay:1,isfloating:1,width:440,height:220,title:Picture-in-Picture

windowrule = isfloating:1, appid:[Ss]team
windowrule = tags:2, isfloating:0, scroller_proportion:0.573, title:Steam
windowrule = isfloating:1, appid:steam, title:Steam Settings

windowrule=isfloating:1,width:1400,height:800,title:Thunar
windowrule=isfloating:1,width:1400,height:800,appid:kew
windowrule=isfloating:1,width:1400,height:800,appid:aethertune
windowrule=force_fakemaximize:1,focused_opacity:1.0,unfocused_opacity:0.8,appid:brave

# layer rule
layerrule=noblur:1,noanim:1,layer_name:selection
layerrule=noblur:1,noanim:1,layer_name:quickshell
layerrule=noblur:1,noanim:1,layer_name:quickshell:popout
layerrule=noblur:1,noanim:1,layer_name:noctalia
layerrule=noblur:1,noanim:1,layer_name:noctalia.*
layerrule=noblur:1,noanim:1,layer_name:dimland_layer
layerrule=noanim:1,layer_name:showkeys
