[main]
include=~/.config/foot/themes/noctalia

shell=fish
#term=xterm-256color
title=foot
font=JetBrainsMono Nerd Font:size=11:style=Medium:antialias=true:autohint=true
pad=8x8
dpi-aware=yes

[colors-dark]
alpha=0.9
alpha-mode=matching
blur=true

[scrollback]
lines=8000
indicator-position=relative

[url]
launch=xdg-open ${url}
osc8-underline=url-mode

[cursor]
style=beam

[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
# primary-paste = Shift+Insert
search-start=Control+f
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0
