# connecting files
$configs = ~/.config/hypr/configs

source=~/.config/hypr/configs/settings.conf
source=~/.config/hypr/configs/environment.conf
source=~/.config/hypr/configs/decoration.conf
source=~/.config/hypr/configs/exec.conf
source=~/.config/hypr/configs/windowrules.conf
source=~/.config/hypr/configs/binds.conf
source=~/.config/hypr/configs/monitor.conf
source=~/.config/hypr/configs/animation.conf

