# Polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &

# Startup
exec-once = vibepanel &
exec-once = awww-daemon -q &
exec-once = awww restore &

exec-once = wl-paste --watch cliphist store &
exec-once = hyprctl --quiet setcursor catppuccin-mocha-light-cursors 24 &

exec-once = gsettings set org.gnome.desktop.interface color-scheme 'default' &

exec-once = xhost +SI:localuser:root &

# Slow app launch fix
exec-once = dbus-update-activation-environment --systemd --all &
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY XAUTHORITY &
exec-once = systemctl --user import-environment &
exec-once = systemctl --user start hyprland-session.target &
