# Floating
windowrule = match:class ^(org.kde.polkit-kde-authentication-agent-1)$, float on, center on
windowrule = match:class ^([Tt]hunar), match:title (Confirm to replace files), float on, center on
windowrule = match:class ^(kvantummanager|pavucontrol|org.pulseaudio.pavucontrol|nwg-look|qt6ct|qt5ct)$, float on, center on
windowrule = match:class ^(Thunar|org.kde.gwenview|[Tt]hunar|Btrfs Assistant|GParted|waypaper)$, float on, center on
windowrule = match:class ^(brave-browser)$, match:title (Messenger call), float on, center on

windowrule = match:title ^(Open File)(.*)$, float on, center on
windowrule = match:title ^(Select a File)(.*)$, float on, center on
windowrule = match:title ^(Choose wallpaper)(.*)$, float on, center on, size (monitor_w*.60) (monitor_h*.65)
windowrule = match:title ^(Open Folder)(.*)$, float on, center on
windowrule = match:title ^(Save As)(.*)$, float on, center on
windowrule = match:title ^(Library)(.*)$, float on, center on
windowrule = match:title ^(File Upload)(.*)$, float on, center on
windowrule = match:title ^(.*)(wants to save)$, float on, center on
windowrule = match:title ^(.*)(wants to open)$, float on, center on
windowrule = match:title ^(File Operation Progress)$, float on, center on
windowrule = match:title ^(Confirm to replace files)$, float on, center on
windowrule = match:class ^(Authentication Required)$, float on, center on

windowrule = match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-hyprland)$, float on, center on
windowrule = match:class ^(CachyOSHello)$, float on, center on
windowrule = match:class ^(foot)$, match:title (yazi|btop|nmtui)$, float on, center on
windowrule = match:class ^(amiberry)$, float on, center on
windowrule = match:class ^(kew)$, float on, center on
windowrule = match:class ^([Ss]team)$, match:title ^([Ss]team)$, float on, center on

windowrule = match:class ^(satty)$, float on, center on

windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Steam
#windowrule = float on, match:class steam
#windowrule = center on, match:class steam, match:title Steam
#windowrule = opacity 1 1, match:class steam.*
windowrule = size 1400 1000, match:class steam, match:title Steam
windowrule = size 460 800, match:class steam, match:title Friends List
windowrule = idle_inhibit fullscreen, match:class steam

# Window Size
windowrule = match:class ^(Thunar|thunar|GParted|Btrfs Assistant|waypaper)$, size 1200 900
windowrule = match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-hyprland)$, size 60% 70%
windowrule = match:class ^(kvantummanager|pavucontrol|org.pulseaudio.pavucontrol|nwg-look|qt6ct|qtc5)$, size 60% 70%
windowrule = match:class ^(foot)$, match:title (yazi|btop|nmtui|update|browser)$, size 60% 80%

workspace = special:magic, on-created-empty:[float] foot
# --title floating

layerrule = match:namespace notifications, blur on
#layerrule = match:namespace gtk-layer-shell, blur on
