[colors.primary]
background = '#121318'
foreground = '#e2e2e9'

[colors.cursor]
text = '#121318'
cursor = '#e2e2e9'

[colors.vi_mode_cursor]
text = '#121318'
cursor = '#b0c6ff'

[colors.search.matches]
foreground = '#44464f'
background = '#e0bbdd'

[colors.search.focused_match]
foreground = '#44464f'
background = '#b0c6ff'

[colors.footer_bar]
foreground = '#44464f'
background = '#e2e2e9'

[colors.hints.start]
foreground = '#44464f'
background = '#c0c6dc'

[colors.hints.end]
foreground = '#44464f'
background = '#c0c6dc'

[colors.selection]
text = '#c5c6d0'
background = '#44464f'


[colors.normal]
black   = '#44464f'
red     = '#ffb4ab'
green   = '#b0c6ff'
yellow  = '#c0c6dc'
blue    = '#e0bbdd'
magenta = '#b0c6ff'
cyan    = '#c0c6dc'
white   = '#e2e2e9'


[colors.bright]
black   = '#8f9099'
red     = '#ffb4ab'
green   = '#b0c6ff'
yellow  = '#c0c6dc'
blue    = '#e0bbdd'
magenta = '#b0c6ff'
cyan    = '#c0c6dc'
white   = '#e2e2e9'


[colors.dim]
black   = '#44464f'
red     = '#ffb4ab'
green   = '#b0c6ff'
yellow  = '#c0c6dc'
blue    = '#e0bbdd'
magenta = '#b0c6ff'
cyan    = '#c0c6dc'
white   = '#e2e2e9'
